# SITE CONFIGURATION
title: Giulliano Paz # your site title
author: giullianopaz # You :P
description: > # Meta description of Homepage
  Blog do Giulliano Paz para compartilhar assuntos e informações sobre programação,
  desenvolvimento, ciência de dados e muitos outros assuntos relacionados à computação.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://giullianopaz.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Giulliano Paz
  links:
    - https://twitter.com/giullianopaz
    - https://www.facebook.com/giulliano.paz
    - https://www.linkedin.com/in/giullianopaz
    - https://github.com/giullianopaz

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'Sobre', link: '/about'}
  - {name: 'Categorias', link: '/categories'}
  - {name: 'Fale Comigo', link: '/contact'}

tagline: >
  be greater than average

hero_img: posts/abandoned_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: giulliano94@gmail.com # email for form submission

twitter_username: giullianopaz # replace with your_twitter_username or comment to remove link from footer
github_username:  giullianopaz # replace with your_github_username or comment to remove link from footer
instagram_username: eu.giullianopaz # replace with your_instagram_username or comment to remove link from footer

disqus:
  shortname: giullianopaz # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
